import AuthContext from "@/context/AuthContext";
import "../globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/home-page/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavBar />
      <div className="">{children}</div>
    </>
  );
}
